components:
  schemas:
    Clothes:
      type: object
      properties:
        name:
          type: string
          example: "Camiseta Chicago Bulls Essential Masculina"
        type:
          type: string
          example: "Camiseta"
        price:
          type: number
          example: 218.49
        description:
          type: object
          properties:
            size:
              type: string
              example: "M"
            color:
              type: string
              example: "Vermelho"
            material:
              type: string
              example: "Algodão"
            brand:
              type: string
              example: "Nike"
            madeIn:
              type: string
              example: "Vietnã"
